### ISSUE TITLE
Having couple of issues

### ISSUE THREAD

**Issue by sarfraznawaz2005** [TiagoSilvaPereira/Laravel-Uploadable#1]
Thanks for nice package!

I am having two issues. First, even if user uploads same image, it is uploaded again because name is encrypted. It would be good if you put an option to clean previous images from uploaded folders such as:

`$cleanPreviousImages = true`

Another issue I am having is that it somehow puts `localhost` in url when I use `$model->getImagePath()` functin. Example:

`<img src="{!! $task->getImagePath('file', 'thumb'); !!}" alt="Image">`

renders as:

`http://localhost/storage/images/tasks/thumb/Ig9asZQ9Ph50FjYIiXBjDJUpNlhupXCI6ng36Dd3.png`

because of that I receive image not found.

Storage driver is also set to public:

`FILESYSTEM_DRIVER=public`

I am using LV5.5

Thanks

**Comment by sarfraznawaz2005** [comment]
I fixed it by setting `APP_URL` to my app url. It would still be good option to have ability of deleting previous images from the folder. Thanks

**Comment by sarfraznawaz2005** [comment]
Can you please also add a method to check if image exists before we use `getImagePath` function otherwise images are not displaying when we always use `getImagePath` hoping user has uploaded something.

Would expect something like this:

```
if ($model->imageExists()) {
   $model->getImagePath();
}
```

**Comment by TiagoSilvaPereira** [comment]
Hi @sarfraznawaz2005 , thank you for using this package. About deleting the files, the package already make it. You can see it on the code of Uploader class: https://github.com/TiagoSilvaPereira/Laravel-Uploadable/blob/master/src/Uploader.php

If it's not working for you, please verify any type of error log on your app and put it here.

About it:

```php
if ($model->imageExists()) {
   $model->getImagePath();
}
```

Yes, I can do it for next versions.

Thank you and enjoy!! 😄

**Comment by sarfraznawaz2005** [comment]
Thanks for the response, yes I see it.
