### ISSUE TITLE
How i can save image with external url

### ISSUE THREAD

**Issue by xblue55** [TiagoSilvaPereira/Laravel-Uploadable#4]
I want download external url facebook image then upload use uploadable.
`https://avatar.facebook.com/hello.jpg`

**Comment by TiagoSilvaPereira** [comment]
Hi @xblue55 you can download the image in the frontend using Javascript, then you can send it to the backend. You can see an example here: https://stackoverflow.com/questions/22923111/downloading-and-then-uploading-files-with-javascript

Closing as it is not a Laravel Uploadable issue.

Cheers!
